<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2e6e9ffa-6fba-4d35-b2b3-95ef4510eec8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\yummy-red-1.0.0\assets\.DS_Store" />
    <None Include="wwwroot\yummy-red-1.0.0\assets\img\.DS_Store" />
    <None Include="wwwroot\yummy-red-1.0.0\assets\vendor\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.18" />
  </ItemGroup>

</Project>
